services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
